apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-ms-deployment
  labels:
    app: homelab-ms 
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: homelab-ms
  template:
    metadata:
      labels:
        app: homelab-ms
    spec:
      containers:
      - name: homelab-ms
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.25"
            memory: "64Mi"
        env:
        - name: NODE_ENV
          value: "production"